behaviors:
    Stickman:
        trainer_type: ppo
        hyperparameters:
            batch_size: 5000
            buffer_size: 50000
            num_epoch: 4
        network_settings:
            hidden_units: 500
            num_layers: 3
#            memory:
#                memory_size: 128
#                sequence_length: 8
        reward_signals:
            extrinsic:
                gamma: 0.99
#            curiosity:
#                strength: 0.1
        time_horizon: 300
        max_steps: 4e7
        threaded: true
        summary_freq: 50000
        #checkpoint_interval: 40000
        keep_checkpoints: 100
engine_settings:
  width: 640
  height: 360